-- Generated by nwg-displays on 2026-08-30 at 15:17:08. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x07A0",
    mode = "1920x1080@59.98",
    position = "0x0",
    scale = 1.0999999999999996
})
